on: 
  push:
   branches:
     - main
name: Deploy website on push
jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Get latest code
      uses: actions/checkout@v4
    
    - name: Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: adisheshyoga.com
        username: admin@adisheshyoga.com
        password: Radhey11@Shyam

    # - name: Install dependencies
    #   run: |
    #     composer install --no-dev --optimize-autoloader

    # - name: Run migrations and seeders
    #   run: |
    #     php artisan migrate --force

    # - name: Optimize cache
    #   run: |
    #     php artisan config:cache
    #     php artisan route:cache
